tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      echo 'TODO: start app'

ports:
  - name: JSON Server
    description: API Data
    port: 3000
    onOpen: open-browser
    visibility: private
  
  - name: environment development
    description: Web Interface
    port: 5173
    onOpen: open-browser
    visibility: private